services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BACKEND_PORT=${BACKEND_PORT:-3000}
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT:-3000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3001}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${FRONTEND_PORT:-3001}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
